/******************************
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*********************************/

#include <iostream>

using namespace std;

#define LIMIT 1000000

int main()
{
    int x = 1;
    int y = 2;
    int temp = 0;
    unsigned sum = 2;

    while ( term2 < LIMIT )
    {
        temp = x;
        x = x + y * 2;
        y = x * 2 + y * 3;
        sum += y;
    }

    cout << sum << endl;
    system("pause");
    return 0;
}